INSERT INTO appointments (NAME_CLIENT, PHONE_CLIENT, SERVICE_TYPE, DATE_APPOINTMENT, CREATIONTIME, UPDATETIME)
VALUES ('Filipe', '123456789', 'HAIRCUT', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('João', '987654321', 'STYLING', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Andreia', '911111111', 'COLORING', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pedro', '922222222', 'STYLING', CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
